name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew reinstall tcl-tk || true
        sudo mkdir -p /usr/local
        sudo ln -sf /usr/local/opt/tcl-tk/include /usr/local/include/tcl8.6
        sudo cp /usr/local/opt/tcl-tk/lib/libtcl* /usr/local/lib
        sudo ln -sf /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh
        sudo ln -sf /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh8.6
    - name: configure
      run: |       
        autoreconf -vi
        ./configure --with-tcl=/usr/local/opt/tcl-tk/lib --prefix=/usr/local        
        ls /private/tmp
    - name: make
      run: |
        make
        make test
    - name: install
      run: sudo make install

